### ISSUE TITLE
How can we give Company Name as an Input to "company_data_scraper"

### ISSUE THREAD

**Issue by AkshayDubey29** [KarthikDani/LinkedIn-Company-Data-Scraping-System#1]
How can we provide input to below command with the company name: 

"scrapy crawl company_profile_scraper -O company_profile_data.json"

**Comment by KarthikDani** [comment]
Well, you can specify the name of the company to `target_company_info` in line 8 of the company_profile_scraper script. I've done this to leverage the scraping for multiple companies, if needed by looping through the `directorydata.json`
